/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
var lastSum = 1;
var previousSum = 2;
var currentSum = 3;

var evenNumberSum = 2;

while ( currentSum < 4000000){
   
    lastSum = previousSum;
    previousSum = currentSum;
    currentSum = previousSum + lastSum;
    
    if (currentSum % 2 == 0 && currentSum < 4000000){
        evenNumberSum = evenNumberSum + currentSum;
    }
}

alert(evenNumberSum);